$(OBJDOSUJO)/cxefo.o: \
pakoj/cxefo/cxefo.c \
pakoj/cxefo/cxef* \
$(OBJDOSUJO)/objekto.o \
$(OBJDOSUJO)/filo.o \
| $(OBJDOSUJO)

	$(CK) $(KFLAGOJ) -c $< \
	-I pakoj/tabelo_de_charoj/ \
	-I pakoj/objekto/ \
	-I pakoj/filo/ \
	-o $@
