$(OBJDOSUJO)cxefo.o: \
$(PAKOJ)cxefo/cxefo.c \
$(PAKOJ)cxefo/cxef* \
$(OBJDOSUJO)objekto.o \
$(OBJDOSUJO)filo.o \
| $(OBJDOSUJO)

	$(CK) $(KFLAGOJ) -c $< \
	-I $(PAKOJ)tabelo_de_charoj/ \
	-I $(PAKOJ)objekto/ \
	-I $(PAKOJ)filo/ \
	-o $@
