$(OBJDOSUJO)tabelo_de_charoj.o: \
$(PAKOJ)tabelo_de_charoj/tabelo_de_charoj.tuta.c \
$(PAKOJ)tabelo_de_charoj/tabelo_de_charoj.tuta.h \
$(PAKOJ)tabelo_de_charoj/tabelo_de_charoj.h \
| $(OBJDOSUJO)
	$(CK) $(KFLAGOJ) -c $< -o $@
