$(OBJDOSUJO)/tabelo_de_charoj.o: \
pakoj/tabelo_de_charoj/tabelo_de_charoj.tuta.c \
pakoj/tabelo_de_charoj/tabelo_de_charoj.tuta.h \
pakoj/tabelo_de_charoj/tabelo_de_charoj.h \
pakoj/objekto/* \
| $(OBJDOSUJO)
	$(CK) $(KFLAGOJ) -c $< -I pakoj/objekto -o $@
